# fly.toml app configuration file generated for tree-appreciation on 2026-02-12T10:59:45Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tree-appreciation'
primary_region = 'ams'

[build]

[env]
  DB_PATH = '/data/prod.db'
  NODE_ENV = 'production'
  PORT = '8080'

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '2gb'
  cpus = 2
  memory_mb = 2048
